[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/password-setup"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"