[build]
  publish = "dist"
  command = "npm run build && mkdir -p dist/src/data && cp -r src/data/* dist/src/data/ 2>/dev/null || true && mkdir -p dist/images && cp -r public/images/* dist/images/ 2>/dev/null || true && mkdir -p dist/admin && cp public/admin/* dist/admin/ 2>/dev/null || true"
  
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  
# Git LFS configuration for large files
[build.processing.images]
  compress = false

# Enable Git Gateway for CMS
[context.production]
  command = "npm run build && mkdir -p dist/src/data && cp -r src/data/* dist/src/data/ 2>/dev/null || true && mkdir -p dist/images && cp -r public/images/* dist/images/ 2>/dev/null || true && mkdir -p dist/admin && cp public/admin/* dist/admin/ 2>/dev/null || true"

[context.deploy-preview]
  command = "npm run build && mkdir -p dist/src/data && cp -r src/data/* dist/src/data/ 2>/dev/null || true && mkdir -p dist/images && cp -r public/images/* dist/images/ 2>/dev/null || true && mkdir -p dist/admin && cp public/admin/* dist/admin/ 2>/dev/null || true"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/password-setup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/src/data/*"
  to = "/src/data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200