[build]
  publish = "dist"
  command = "npm run build && mkdir -p dist/images && cp -r public/images/* dist/images/ 2>/dev/null || true"
  
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/password-setup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/src/data/*"
  to = "/src/data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200