backend:
  name: git-gateway
  branch: main

publish_mode: simple
media_folder: "public/images"
public_folder: "/images"
site_url: https://onafricatp.com
display_url: https://onafricatp.com
logo_url: https://i.postimg.cc/x8zq9Qvf/2025-06-29-T075316-796.png


collections:
  - name: "site"
    label: "Paramètres du site"
    files:
      - file: "src/data/site.json"
        label: "Informations générales"
        name: "site"
        fields:
          - {label: "Nom du site", name: "title", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - {label: "Logo", name: "logo", widget: "image", required: true}

  - name: "hero"
    label: "Section Accueil"
    files:
      - file: "src/data/hero.json"
        label: "Contenu Accueil"
        name: "hero"
        fields:
          - {label: "Image de fond", name: "backgroundImage", widget: "image", required: true}
          - {label: "Titre principal", name: "title", widget: "string", required: true}
          - {label: "Sous-titre coloré", name: "subtitle", widget: "string", required: true}
          - {label: "Texte du bouton", name: "buttonText", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - label: "Statistiques"
            name: "stats"
            widget: "list"
            min: 4
            max: 4
            collapsed: false
            fields:
              - {label: "Nombre", name: "number", widget: "number", required: true}
              - {label: "Suffixe", name: "suffix", widget: "string", required: true}
              - {label: "Libellé", name: "label", widget: "string", required: true}

  - name: "presentation"
    label: "Section Présentation"
    files:
      - file: "src/data/presentation.json"
        label: "Contenu Présentation"
        name: "presentation"
        fields:
          - {label: "Titre", name: "title", widget: "string", required: true}
          - {label: "Sous-titre", name: "subtitle", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - {label: "Image", name: "image", widget: "image", required: true}

  - name: "director"
    label: "Le mot du directeur"
    files:
      - file: "src/data/director.json"
        label: "Message du Directeur"
        name: "director"
        fields:
          - {label: "Titre de la section", name: "title", widget: "string", required: true, default: "Le mot du directeur"}
          - {label: "Photo du directeur", name: "image", widget: "image", required: true}
          - {label: "Citation principale", name: "quote", widget: "text", required: true}
          - {label: "Message complet du directeur", name: "message", widget: "text", required: true}

  - name: "services"
    label: "Nos services"
    files:
      - file: "src/data/services.json"
        label: "Services et Valeurs"
        name: "services"
        fields:
          - {label: "Titre de la section", name: "title", widget: "string", required: true, default: "Nos Services"}
          - {label: "Description de la section", name: "description", widget: "text", required: true}
          - label: "Liste des services"
            name: "servicesList"
            widget: "list"
            min: 7
            max: 7
            collapsed: false
            summary: "{{fields.title}}"
            fields:
              - {label: "Nom du service", name: "title", widget: "string", required: true}
              - {label: "Image du service", name: "image", widget: "image", required: true}
              - {label: "Icône Lucide", name: "icon", widget: "string", required: true, hint: "Noms d'icônes: Building, Truck, Wrench, Droplets, Package, Car, Plus"}
          - label: "Mission, Vision, Valeurs"
            name: "values"
            widget: "list"
            min: 3
            max: 3
            collapsed: false
            summary: "{{fields.title}}"
            fields:
              - {label: "Titre (Mission/Vision/Valeurs)", name: "title", widget: "string", required: true}
              - {label: "Description", name: "description", widget: "text", required: true}
              - {label: "Emoji", name: "icon", widget: "string", required: true, hint: "Exemples: 🎯, 👁️, 💎"}

  - name: "projects"
    label: "Nos réalisations"
    files:
      - file: "src/data/projects.json"
        label: "Portfolio de Réalisations"
        name: "projects"
        fields:
          - {label: "Titre de la section", name: "title", widget: "string", required: true, default: "Nos Réalisations"}
          - {label: "Description de la section", name: "description", widget: "text", required: true}
          - label: "Liste des projets"
            name: "projectsList"
            widget: "list"
            collapsed: false
            summary: "{{fields.title}}"
            fields:
              - {label: "Titre du projet", name: "title", widget: "string", required: true}
              - {label: "Image du projet", name: "image", widget: "image", required: true}

  - name: "partners"
    label: "Section Partenaires"
    files:
      - file: "src/data/partners.json"
        label: "Nos Partenaires"
        name: "partners"
        fields:
          - {label: "Titre", name: "title", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - label: "Partenaires"
            name: "partnersList"
            widget: "list"
            collapsed: false
            summary: "{{fields.name}}"
            fields:
              - {label: "Nom du partenaire", name: "name", widget: "string", required: true}
              - {label: "Logo du partenaire", name: "image", widget: "image", required: true}

  - name: "contact"
    label: "Section Contact"
    files:
      - file: "src/data/contact.json"
        label: "Informations de Contact"
        name: "contact"
        fields:
          - {label: "Titre de la section", name: "title", widget: "string", required: true, default: "Contactez-nous"}
          - {label: "Description de la section", name: "description", widget: "text", required: true}
          - {label: "Numéro de téléphone fixe", name: "phone", widget: "string", required: true, hint: "Format: +222 25901252"}
          - {label: "Numéro de mobile", name: "mobile", widget: "string", required: true, hint: "Format: +222 28880729"}
          - {label: "Numéro WhatsApp", name: "whatsapp", widget: "string", required: true, hint: "Format: +222 666 39 63 36"}
          - {label: "Adresse email", name: "email", widget: "string", required: true, hint: "Format: contact@onafricatp.com"}

  - name: "footer"
    label: "Pied de page"
    files:
      - file: "src/data/footer.json"
        label: "Contenu du Footer"
        name: "footer"
        fields:
          - {label: "Description de l'entreprise", name: "description", widget: "text", required: true}
          - {label: "Copyright", name: "copyright", widget: "string", required: true}