backend:
  name: git-gateway
  branch: main

publish_mode: simple
media_folder: public/images
public_folder: /images
site_url: https://onafricatp.com
display_url: https://onafricatp.com
logo_url: https://i.postimg.cc/x8zq9Qvf/2025-06-29-T075316-796.png

# Enable media library for image uploads
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: "site"
    label: "Paramètres du site"
    files:
      - file: "src/data/site.json"
        label: "Informations générales"
        name: "site"
        fields:
          - {label: "Nom du site", name: "title", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - {label: "Logo", name: "logo", widget: "image", required: true}

  - name: "hero"
    label: "Section Accueil"
    files:
      - file: "src/data/hero.json"
        label: "Contenu Accueil"
        name: "hero"
        fields:
          - {label: "Image de fond", name: "backgroundImage", widget: "image", required: true}
          - {label: "Titre principal", name: "title", widget: "string", required: true}
          - {label: "Sous-titre coloré", name: "subtitle", widget: "string", required: true}
          - {label: "Texte du bouton", name: "buttonText", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - label: "Statistiques"
            name: "stats"
            widget: "list"
            min: 4
            max: 4
            collapsed: false
            fields:
              - {label: "Nombre", name: "number", widget: "number", required: true}
              - {label: "Suffixe", name: "suffix", widget: "string", required: true}
              - {label: "Libellé", name: "label", widget: "string", required: true}

  - name: "presentation"
    label: "Section Présentation"
    files:
      - file: "src/data/presentation.json"
        label: "Contenu Présentation"
        name: "presentation"
        fields:
          - {label: "Titre", name: "title", widget: "string", required: true}
          - {label: "Sous-titre", name: "subtitle", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - {label: "Image", name: "image", widget: "image", required: true}

  - name: "director"
    label: "Section Directeur"
    files:
      - file: "src/data/director.json"
        label: "Message du Directeur"
        name: "director"
        fields:
          - {label: "Titre", name: "title", widget: "string", required: true}
          - {label: "Photo du directeur", name: "image", widget: "image", required: true}
          - {label: "Citation", name: "quote", widget: "text", required: true}
          - {label: "Message complet", name: "message", widget: "text", required: true}

  - name: "services"
    label: "Section Services"
    files:
      - file: "src/data/services.json"
        label: "Nos Services"
        name: "services"
        fields:
          - {label: "Titre", name: "title", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - label: "Liste des services"
            name: "servicesList"
            widget: "list"
            min: 7
            max: 7
            collapsed: false
            fields:
              - {label: "Nom du service", name: "title", widget: "string", required: true}
              - {label: "Image", name: "image", widget: "image", required: true}
              - {label: "Icône (nom Lucide)", name: "icon", widget: "string", required: true, hint: "Utilisez les noms d'icônes Lucide comme: Building, Truck, Wrench, Droplets, Package, Car, Plus"}
          - label: "Mission, Vision, Valeurs"
            name: "values"
            widget: "list"
            min: 3
            max: 3
            collapsed: false
            fields:
              - {label: "Titre", name: "title", widget: "string", required: true}
              - {label: "Description", name: "description", widget: "text", required: true}
              - {label: "Emoji", name: "icon", widget: "string", required: true, hint: "Utilisez un emoji comme: 🎯, 👁️, 💎"}

  - name: "projects"
    label: "Section Réalisations"
    files:
      - file: "src/data/projects.json"
        label: "Nos Réalisations"
        name: "projects"
        fields:
          - {label: "Titre", name: "title", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - label: "Projets"
            name: "projectsList"
            widget: "list"
            collapsed: false
            fields:
              - {label: "Titre du projet", name: "title", widget: "string", required: true}
              - {label: "Image", name: "image", widget: "image", required: true}

  - name: "partners"
    label: "Section Partenaires"
    files:
      - file: "src/data/partners.json"
        label: "Nos Partenaires"
        name: "partners"
        fields:
          - {label: "Titre", name: "title", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - label: "Partenaires"
            name: "partnersList"
            widget: "list"
            collapsed: false
            fields:
              - {label: "Nom du partenaire", name: "name", widget: "string", required: true}
              - {label: "Logo du partenaire", name: "image", widget: "image", required: true}

  - name: "contact"
    label: "Section Contact"
    files:
      - file: "src/data/contact.json"
        label: "Informations de Contact"
        name: "contact"
        fields:
          - {label: "Titre", name: "title", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "text", required: true}
          - {label: "Téléphone", name: "phone", widget: "string", required: true}
          - {label: "Mobile", name: "mobile", widget: "string", required: true}
          - {label: "WhatsApp", name: "whatsapp", widget: "string", required: true}
          - {label: "Email", name: "email", widget: "string", required: true}

  - name: "footer"
    label: "Pied de page"
    files:
      - file: "src/data/footer.json"
        label: "Contenu du Footer"
        name: "footer"
        fields:
          - {label: "Description de l'entreprise", name: "description", widget: "text", required: true}
          - {label: "Copyright", name: "copyright", widget: "string", required: true}